services:
  # 这里的 collector 是你的服务名称
  collector:
    build: .                # 告诉它去当前目录找 Dockerfile 构建镜像
    container_name: collector-server
    restart: always         # 关键：程序崩溃或交易所断线导致退出时，自动重启

    # 环境变量管理
    env_file:
      - .env                # 自动加载你的 API Key 等敏感信息

    # 数据持久化（非常重要！）
    volumes:
      - ./data:/app/data    # 把容器内的 /app/data 映射到你电脑的 ./data 文件夹
      - ./logs:/app/logs    # 映射日志，方便排查
      - ./src:/app/src
      # - ./main.py:/app/main.py
    
    environment:
      - PYTHONPATH=/app

    command: python /app/src/collectors/stream_manager.py

    # 资源限制（防止 Polars 瞬间吃光服务器内存）
    deploy:
      resources:
        limits:
          memory: 10G
        reservations:
          memory: 4G

    depends_on:
      - quant_redis
      - clickhouse

  syncer:
    build: .
    container_name: syncer-server
    restart: always

    env_file:
      - .env

    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./src:/app/src

    environment:
      - PYTHONPATH=/app

    command: python /app/src/workers/db_syncer.py

    deploy:
      resources:
        limits:
          memory: 10G
        reservations:
          memory: 4G

    depends_on:
      - quant_redis
      - clickhouse

  gap_filler:
    build: .
    container_name: gap-filler-worker
    restart: always

    env_file:
      - .env

    volumes:
      - ./logs:/app/logs
      - ./src:/app/src

    environment:
      - PYTHONPATH=/app

    command: python /app/src/workers/gap_filler.py

    deploy:
      resources:
        limits:
          memory: 10G
        reservations:
          memory: 4G

    depends_on:
      - quant_redis
      - clickhouse

  #控制组件
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./infra/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./infra/monitoring/prometheus/prometheus_data:/prometheus
    ports:
      - "9090:9090"
    
  pushgateway:
    image: prom/pushgateway:latest
    ports:
      - "9091:9091"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=administration
    volumes:
      - ./infra/monitoring/grafana/grafana_data:/var/lib/grafana
    user: "472"   # 关键：Grafana 容器内部默认使用 ID 为 472 的用户，需要对齐权限
    depends_on:
      - prometheus

  quant_redis:
    image: redis:alpine
    container_name: quant_redis_service
    ports:
      - "6380:6379"
    command: redis-server --maxmemory 2gb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: 2.5G

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=martin1510
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./infra/clickhouse/clickhouse_data:/var/lib/clickhouse
      - ./infra/clickhouse/clickhouse_logs:/var/log/clickhouse-server
      - ./data:/var/lib/clickhouse/user_files/data
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  