global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'daily_patching'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
  - job_name: 'collector'
    static_configs:
      - targets: ['pushgateway:9091']
